export const PLAYING_HEIGHT = 106;
export const HEADER_PROFILE_HEIGHT = 60
export const HEADER_PROFILE_PADDING_VERTICAL = 60


export const SEARCH_BAR_HEIGHT = 40;
export const PADDING_TOP_BAR = 16;

export const HEADER_FULL_HEIGHT =  HEADER_PROFILE_HEIGHT + HEADER_PROFILE_PADDING_VERTICAL * 2 + PADDING_TOP_BAR;
export const HEADER_MIN_HEIGHT =  HEADER_PROFILE_PADDING_VERTICAL + PADDING_TOP_BAR;

export const HEADER_SCROLL_DISTANCE = HEADER_FULL_HEIGHT - HEADER_MIN_HEIGHT;


